apiVersion: v1
kind: Secret
metadata:
  name: stock-secret
type: Opaque
stringData:
    appsettings.Development.json: |-
            {
                "Serilog": {
                "MinimumLevel": {
                    "Default": "Information",
                    "Override": {
                    "Microsoft": "Information",
                    "System": "Warning"
                    }
                }
                },

                "IdentityUrl": "http://authserver:80",

                "UsedHostNames": [
                "http://localhost:4100",
                "http://localhost:4200"
                ],
                "ConnectionStrings": {
                "ApplicationDbContext": "Server=stockdbv2.cyxqtem3lhop.ap-northeast-1.rds.amazonaws.com;Port=5432;Database=stockdbv2;User Id=postgres;Password=Password;"
                }

            }


