apiVersion: v1
kind: Secret
metadata:
  name: transaction-secret
type: Opaque
stringData:
    appsettings.Development.json: |-
                              {
                                  "Serilog": {
                                    "MinimumLevel": {
                                      "Default": "Information",
                                      "Override": {
                                        "Microsoft": "Information",
                                        "System": "Warning"
                                      }
                                    }
                                  },

                                  "LogFileName": "UserServiceLogs.txt",

                                  "IdentityUrl": "http://authserver:80",

                              

                                  "DataProtectionTokenProviderOptions": {
                                    "TokenLifeSpanInHours": "2"
                                  },

                                  "EmailConfirmationTokenProviderOptions": {
                                    "TokenLifeSpanInHours": "72"
                                  },

                                  "LockoutIdenityOptions": {
                                    "MaxFailedAccessAttempts": "10",
                                    "DefaultLockoutTimeSpanInMinutes": "5"
                                  },

                                  "IdentityClientRegistration": {
                                    "TokenEndpoint": "http://authserver:80/connect/token",
                                    "ClientId": "ro.client",
                                    "ClientSecret": "secret"
                                  },

                                  "UsedHostNames": [
                                    "http://localhost:4100",
                                    "http://localhost:4200",
                                      "*"
                                  ],
                                  "ConnectionStrings": {
                                    "ApplicationDbContext": "Server=stockdbv2.cyxqtem3lhop.ap-northeast-1.rds.amazonaws.com;Port=5432;Database=stockdbv2;User Id=postgres;Password=Password;"
                                  }
                              }


