apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: default
  labels:
    name: user
    app: CloudSE
spec:
  type: NodePort
  ports:
    - port: 80 # anyting tag to service used internally 
      targetPort: 80 #image port
      nodePort: 31002 # outside
  selector:
    name: user-pod
    app: CloudSE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
  labels:
    app: CloudSE
    name: user-service
spec:
  template:
    metadata:
      name: user-pod
      labels:
        name: user-pod
        app: CloudSE
    spec:
      imagePullSecrets:
        - name: regcred  #ecr user secret
      containers:
        - name: user-pod
          image: 377379411010.dkr.ecr.ap-northeast-1.amazonaws.com/se:UserService23 # {"$imagepolicy": "flux-system:identity"}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "200Mi" #megabytes
              cpu: "200m"   #.05 core
            limits:
              memory: "250Mi" #issues log file : OOM killed
              cpu: "250m"
          ports:
            - containerPort: 80 #
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
      volumes:
        - name: appsettings-volume
          secret:
            secretName: user-secret
            # configMap:
            #     name: identity-configmap
  replicas: 1
  selector:
    matchLabels:
      app: CloudSE 
