apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/isujeewa/CCSE_DotNetCore.git
    targetRevision: HEAD
    path: DevOps
  destination:
    server: https://kubernetes.default.svc
    namespace: default